### ISSUE TITLE
500 Internal Server error trying to start backyards dashboard

### ISSUE THREAD

**Issue by eddiewang** [banzaicloud/backyards-cli#153]
**Describe the bug**
```
failed to log in, you may need to install backyards first: server error: 500 Internal Server Error `{"type":"about:blank","title":"Internal Server Error","status":500,"ErrorCode":""}
```
Whenever `backyards dashboard` is run. I am able to do `kubectl port-forward` into the web service, but then I get an graphql  auth error from the web-ui when trying to access the data.

I believe it may be because I am using a Gravity cluster, and accessing the cluster via `Teleport`.

**Comment by Laci21** [comment]
You can run backyards commands with a debug flag to see if there are any other relevant info there: `backyards -v dashboard`

You can check if the pods are actually up and running in the `backyards-system` namespace with: `kubectl get po -n=backyards-system`

You can check the logs of the `backyards` container in the `backyards-...` pod with: `kubectl logs -n=backyards-system backyards-... backyards`

As a workaround you might try and see if this works: `backyards -v dashboard --use-portforward`
(The `--use-portforward` switch uses port forwarding instead of proxying the service.)
